# Generated by Django 2.0.7 on 2018-08-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='palypath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100, verbose_name='playbook路径')),
                ('func', models.CharField(max_length=100, verbose_name='功能')),
            ],
            options={
                'verbose_name': 'func',
                'verbose_name_plural': 'func',
                'db_table': 'root_user',
            },
        ),
    ]
