# Generated by Django 2.0.7 on 2018-08-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansibleControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='palypath',
            table='playbook',
        ),
    ]
