# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-16 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='账户')),
                ('passwd', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
                ('ip', models.GenericIPAddressField()),
                ('user_check', models.BooleanField()),
            ],
            options={
                'verbose_name': '服务器账号',
                'verbose_name_plural': '服务器账号',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='account_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='账户')),
                ('passwd', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
                ('ip', models.GenericIPAddressField()),
                ('user_check', models.BooleanField()),
            ],
            options={
                'verbose_name': '服务器账号申请',
                'verbose_name_plural': '服务器账号申请',
                'db_table': 'account_apply',
            },
        ),
        migrations.AlterUniqueTogether(
            name='account_apply',
            unique_together=set([('ip', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('ip', 'email')]),
        ),
    ]
