# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-04 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='账户')),
                ('passwd', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
                ('ip', models.GenericIPAddressField()),
                ('user_check', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'account_information',
                'verbose_name': 'account_information',
            },
        ),
    ]
