# Generated by Django 2.0.7 on 2018-08-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nagios_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Responsible', models.CharField(max_length=100, verbose_name='业务负责人')),
                ('Business_name', models.CharField(max_length=100, verbose_name='业务名称')),
                ('url', models.CharField(max_length=100, verbose_name='访问地址')),
            ],
            options={
                'verbose_name_plural': 'Business_name',
                'verbose_name': 'Business_name',
                'db_table': 'nagioslog',
            },
        ),
    ]
